export type Language = "en" | "hi" | "hinglish";

export type TemplateMeta = {
  id: string;
  title: string;
  slug: string;
  languages: Language[];
  accent: string; // Tailwind gradient classes, e.g. "from-orange-400 via-rose-400 to-fuchsia-500"
  thumbnail: string; // /assets/thumbnails/<slug>.jpg
  tags: string[];
  kind: "invite" | "wish"; // NEW: differentiate festival invites vs daily wishes
};

export const templates: TemplateMeta[] = [
  // ==== Existing (now marked as invites) ====
  {
    id: "ganesh",
    title: "Ganesh Chaturthi",
    slug: "ganesh-chaturthi",
    languages: ["en", "hi", "hinglish"],
    accent: "from-orange-400 via-rose-400 to-fuchsia-500",
    thumbnail: "/assets/thumbnails/ganesh.jpg",
    tags: ["festival", "devotional", "vibrant"],
    kind: "invite",
  },
  {
    id: "diwali",
    title: "Diwali",
    slug: "diwali",
    languages: ["en", "hi", "hinglish"],
    accent: "from-amber-400 via-orange-400 to-rose-500",
    thumbnail: "/assets/thumbnails/diwali.jpg",
    tags: ["festival", "lights", "gold"],
    kind: "invite",
  },
  {
    id: "janmashtami",
    title: "Janmashtami",
    slug: "janmashtami",
    languages: ["en", "hi", "hinglish"],
    accent: "from-sky-400 via-indigo-400 to-violet-500",
    thumbnail: "/assets/thumbnails/janmashtami.jpg",
    tags: ["festival", "divine", "elegant"],
    kind: "invite",
  },
  {
    id: "navratri",
    title: "Navratri",
    slug: "navratri",
    languages: ["en", "hi", "hinglish"],
    accent: "from-pink-400 via-rose-400 to-orange-500",
    thumbnail: "/assets/thumbnails/navratri.jpg",
    tags: ["festival", "garba", "vibrant"],
    kind: "invite",
  },
  {
    id: "birthday",
    title: "Birthday",
    slug: "birthday",
    languages: ["en", "hi", "hinglish"],
    accent: "from-fuchsia-400 via-rose-400 to-amber-400",
    thumbnail: "/assets/thumbnails/birthday.jpg",
    tags: ["personal", "confetti"],
    kind: "invite",
  },
  {
    id: "anniversary",
    title: "Anniversary",
    slug: "anniversary",
    languages: ["en", "hi", "hinglish"],
    accent: "from-rose-400 via-pink-400 to-purple-500",
    thumbnail: "/assets/thumbnails/anniversary.jpg",
    tags: ["personal", "romantic"],
    kind: "invite",
  },
  {
    id: "newyear",
    title: "New Year",
    slug: "new-year",
    languages: ["en", "hi", "hinglish"],
    accent: "from-amber-400 via-yellow-400 to-rose-500",
    thumbnail: "/assets/thumbnails/newyear.jpg",
    tags: ["celebration", "sparkle"],
    kind: "invite",
  },
  {
    id: "ramzan",
    title: "Ramzan/Eid",
    slug: "eid",
    languages: ["en", "hi", "hinglish"],
    accent: "from-emerald-400 via-teal-400 to-cyan-500",
    thumbnail: "/assets/thumbnails/eid.jpg",
    tags: ["festival", "crescent"],
    kind: "invite",
  },

  // ==== More festivals ====
  {
    id: "holi",
    title: "Holi",
    slug: "holi",
    languages: ["en", "hi", "hinglish"],
    accent: "from-pink-400 via-fuchsia-400 to-violet-500",
    thumbnail: "/assets/thumbnails/holi.jpg",
    tags: ["festival", "color", "vibrant"],
    kind: "invite",
  },
  {
    id: "raksha-bandhan",
    title: "Raksha Bandhan",
    slug: "raksha-bandhan",
    languages: ["en", "hi", "hinglish"],
    accent: "from-amber-400 via-rose-400 to-pink-500",
    thumbnail: "/assets/thumbnails/raksha-bandhan.jpg",
    tags: ["festival", "siblings", "thread"],
    kind: "invite",
  },
  {
    id: "lohri",
    title: "Lohri",
    slug: "lohri",
    languages: ["en", "hi", "hinglish"],
    accent: "from-orange-400 via-amber-400 to-yellow-500",
    thumbnail: "/assets/thumbnails/lohri.jpg",
    tags: ["festival", "bonfire", "punjabi"],
    kind: "invite",
  },
  {
    id: "makar-sankranti",
    title: "Makar Sankranti",
    slug: "makar-sankranti",
    languages: ["en", "hi", "hinglish"],
    accent: "from-sky-400 via-cyan-400 to-indigo-500",
    thumbnail: "/assets/thumbnails/makar-sankranti.jpg",
    tags: ["festival", "kites", "harvest"],
    kind: "invite",
  },
  {
    id: "pongal",
    title: "Pongal",
    slug: "pongal",
    languages: ["en", "hi", "hinglish"],
    accent: "from-amber-400 via-lime-400 to-emerald-500",
    thumbnail: "/assets/thumbnails/pongal.jpg",
    tags: ["festival", "harvest", "south-india"],
    kind: "invite",
  },
  {
    id: "onam",
    title: "Onam",
    slug: "onam",
    languages: ["en", "hi", "hinglish"],
    accent: "from-lime-400 via-emerald-400 to-teal-500",
    thumbnail: "/assets/thumbnails/onam.jpg",
    tags: ["festival", "pookalam", "south-india"],
    kind: "invite",
  },
  {
    id: "karwa-chauth",
    title: "Karwa Chauth",
    slug: "karwa-chauth",
    languages: ["en", "hi", "hinglish"],
    accent: "from-rose-400 via-pink-400 to-red-500",
    thumbnail: "/assets/thumbnails/karwa-chauth.jpg",
    tags: ["festival", "fasting", "moon"],
    kind: "invite",
  },
  {
    id: "bhai-dooj",
    title: "Bhai Dooj",
    slug: "bhai-dooj",
    languages: ["en", "hi", "hinglish"],
    accent: "from-fuchsia-400 via-rose-400 to-amber-400",
    thumbnail: "/assets/thumbnails/bhai-dooj.jpg",
    tags: ["festival", "siblings"],
    kind: "invite",
  },
  {
    id: "ram-navami",
    title: "Ram Navami",
    slug: "ram-navami",
    languages: ["en", "hi", "hinglish"],
    accent: "from-amber-400 via-orange-400 to-red-500",
    thumbnail: "/assets/thumbnails/ram-navami.jpg",
    tags: ["festival", "devotional"],
    kind: "invite",
  },
  {
    id: "hanuman-jayanti",
    title: "Hanuman Jayanti",
    slug: "hanuman-jayanti",
    languages: ["en", "hi", "hinglish"],
    accent: "from-orange-400 via-amber-400 to-rose-500",
    thumbnail: "/assets/thumbnails/hanuman-jayanti.jpg",
    tags: ["festival", "devotional"],
    kind: "invite",
  },
  {
    id: "eid-adha",
    title: "Eid al-Adha",
    slug: "eid-al-adha",
    languages: ["en", "hi", "hinglish"],
    accent: "from-emerald-400 via-teal-400 to-green-500",
    thumbnail: "/assets/thumbnails/eid-al-adha.jpg",
    tags: ["festival", "crescent"],
    kind: "invite",
  },
  {
    id: "christmas",
    title: "Christmas",
    slug: "christmas",
    languages: ["en", "hi", "hinglish"],
    accent: "from-emerald-400 via-green-400 to-red-500",
    thumbnail: "/assets/thumbnails/christmas.jpg",
    tags: ["festival", "winter", "tree"],
    kind: "invite",
  },

  // ==== Daily wishes (lightweight; date/venue optional) ====
  {
    id: "good-morning",
    title: "Good Morning",
    slug: "good-morning",
    languages: ["en", "hi", "hinglish"],
    accent: "from-amber-300 via-orange-300 to-rose-400",
    thumbnail: "/assets/thumbnails/good-morning.jpg",
    tags: ["wish", "daily", "greeting"],
    kind: "wish",
  },
  {
    id: "good-night",
    title: "Good Night",
    slug: "good-night",
    languages: ["en", "hi", "hinglish"],
    accent: "from-indigo-400 via-violet-400 to-fuchsia-500",
    thumbnail: "/assets/thumbnails/good-night.jpg",
    tags: ["wish", "daily", "greeting"],
    kind: "wish",
  },
  {
    id: "congratulations",
    title: "Congratulations",
    slug: "congratulations",
    languages: ["en", "hi", "hinglish"],
    accent: "from-yellow-400 via-amber-400 to-orange-500",
    thumbnail: "/assets/thumbnails/congratulations.jpg",
    tags: ["wish", "achievement", "celebration"],
    kind: "wish",
  },
  {
    id: "best-of-luck",
    title: "Best of Luck",
    slug: "best-of-luck",
    languages: ["en", "hi", "hinglish"],
    accent: "from-teal-400 via-cyan-400 to-sky-500",
    thumbnail: "/assets/thumbnails/best-of-luck.jpg",
    tags: ["wish", "exam", "support"],
    kind: "wish",
  },
  {
    id: "get-well-soon",
    title: "Get Well Soon",
    slug: "get-well-soon",
    languages: ["en", "hi", "hinglish"],
    accent: "from-rose-300 via-pink-300 to-emerald-300",
    thumbnail: "/assets/thumbnails/get-well-soon.jpg",
    tags: ["wish", "care", "health"],
    kind: "wish",
  },
  {
    id: "thank-you",
    title: "Thank You",
    slug: "thank-you",
    languages: ["en", "hi", "hinglish"],
    accent: "from-amber-300 via-yellow-300 to-lime-400",
    thumbnail: "/assets/thumbnails/thank-you.jpg",
    tags: ["wish", "gratitude"],
    kind: "wish",
  },
  {
    id: "durga-puja",
    title: "Durga Puja",
    slug: "durga-puja",
    languages: ["en", "hi", "hinglish"],
    accent: "from-rose-600 via-red-500 to-amber-500",
    thumbnail: "/assets/thumbnails/durga-puja.jpg",
    tags: ["festival", "bengal", "dhak"],
    kind: "invite",
  },
  {
    id: "chhath",
    title: "Chhath Puja",
    slug: "chhath",
    languages: ["en", "hi", "hinglish"],
    accent: "from-amber-500 via-emerald-500 to-cyan-500",
    thumbnail: "/assets/thumbnails/chhath.jpg",
    tags: ["festival", "devotional", "sun"],
    kind: "invite",
  },
  {
    id: "baisakhi",
    title: "Baisakhi",
    slug: "baisakhi",
    languages: ["en", "hi", "hinglish"],
    accent: "from-yellow-400 via-amber-500 to-orange-500",
    thumbnail: "/assets/thumbnails/baisakhi.jpg",
    tags: ["festival", "punjabi", "harvest"],
    kind: "invite",
  },
  {
    id: "vishu",
    title: "Vishu",
    slug: "vishu",
    languages: ["en", "hi", "hinglish"],
    accent: "from-amber-400 via-yellow-500 to-green-500",
    thumbnail: "/assets/thumbnails/vishu.jpg",
    tags: ["festival", "kerala", "new-year"],
    kind: "invite",
  },
];
